version: "3.7"
services:
  app:
    env_file:
     - .env
    container_name: audit-policy
    image: audit-policy:latest
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - "./:/opt/audit-policy"
